manifest:
  remotes:
    - name: upstream
      url-base: https://github.com/zmkfirmware
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: caksoylar
      revision: caksoylar/experimental
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-tri-state
      remote: caksoylar
      revision: main
    # ZMK with Zephyr namespaced under /zmk. This requires that ZMK imports
    # Zephyr with a path other than `zephyr` (as in `going-modular`).
    - name: zmk
      revision: going-modular
      path: .
      import:
        file: app/west.yml
        path-prefix: zmk
  self:
    path: config
