manifest:
  remotes:
    - name: upstream
      url-base: https://github.com/zmkfirmware
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: urob
      url-base: https://github.com/urob
    - name: duanexavierbondad
      url-base: https://github.com/duanexavierbondad
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: infused-kim
      revision: pr-testing/mouse_ps2_module_base
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-tri-state
      remote: duanexavierbondad
      revision: main
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: infused-kim
      revision: main
  self:
    path: config
